### ISSUE TITLE
Res2Net-50-L with 18w x 4s

### ISSUE THREAD

**Issue by hammer422** [4uiiurz1/pytorch-res2net#1]
文章说Res2Net-50-L with 18w x 4s。这个宽度为18是怎么实现的，因为18 % 4=2啊，难道不是等分的

**Comment by 4uiiurz1** [comment]
Sorry, I can't read Chinese.

**Comment by hammer422** [comment]
The paper mentioned that Res2net-50-L with 18w x 4s ,18 means width of the filters & 4 means scales.So my question is that 18 mod 4 is not equal 0, and in your codes,you wirte this in res2netbottleneck
`if planes % scales != 0:
            raise ValueError('Planes must be divisible by scales')`
So Is it my wrong understanding?
last,Thank you for your excellent work.

**Comment by 4uiiurz1** [comment]
I have fixed it!
