### ISSUE TITLE
Res2net预训练模型

### ISSUE THREAD

**Issue by yile824** [4uiiurz1/pytorch-res2net#2]
因为计算资源有限，想问您要在imagenet上预训练的res2net50的模型

**Comment by 4uiiurz1** [comment]
I can't read Chinese.

**Comment by XingLiuJia** [comment]
> 因为计算资源有限，想问您要在imagenet上预训练的res2net请问你有吗？能分享一下吗

**Comment by XingLiuJia** [comment]
你好，请问你有res2net50或者101的预训练模型吗？能分享一下吗

**Comment by XingLiuJia** [comment]
> 因为计算资源有限，想问您要在imagenet上预训练的res2net50的模型

你好，能分享一下您的预训练模型吗？ res2net50或者101 的，感谢！1
