### ISSUE TITLE
As to pre-trained model

### ISSUE THREAD

**Issue by ShaoqingHan123** [4uiiurz1/pytorch-res2net#4]
I'm in great need of a pre-trained Res2Net model to init a model in my object-detection project,could you please provide the parameters of yours?

**Comment by 4uiiurz1** [comment]
Sorry, I don't have the computing resources to train on ImageNet.

**Comment by D201830280253** [comment]
> Sorry, I don't have the computing resources to train on ImageNet.

okay,no problem.
